### PR TITLE
fixed syncing

### PR DESCRIPTION
**Pull request by auamod**

### CODE REVIEW

**Comment by fkooman** [comment]
What was actually broken here?

**Comment by auamod** [comment]
The scope of the sync.WaitGroup was globally used.
Problems arise when multiple calls are made, efficiency-related issues in this case.

Let say 2 LIST-calls are made by different instances. Since both calls will be using the same WaitGroup, they will both have to wait for the other to finish.

**Comment by auamod** [comment]
If we create one WaitGroup for each call, no calls will have to wait for another calls to finish

**Comment by fkooman** [comment]
I probably did this for a reason... but not sure why.

The OpenVPN management port blocks when there already is a connection, i.e. it doesn't allow it and makes the caller wait until the other connection is closed. Could that have anything to do with it?

**Comment by auamod** [comment]
In this case if its being blocked or not, will have no effect.

https://github.com/letsconnectvpn/lc-daemon/blob/88e8e7badee3e26c3aa45653a30009f2ec8b91a6/lc-daemon/main.go#L122

Lets say 2 calls are made for LIST (or DISCONNECT): They will both add a counter to same WaitGroup. But they will both have to wait for the counter to reach 0(calling wg.done will reduce the counter by 1), so in other words both of the calls will have to wait for eachother.

 In my case since they will have there own WaitGroup, remaining in their respective scope and not touching any other part of the program

**Comment by fkooman** [comment]
Merged!

**Pull request closed without merging**
